# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 21:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20160928_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='TxdToken',
            fields=[
                ('idtoken', models.AutoField(db_column='idToken', primary_key=True, serialize=False)),
                ('token', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'txd_Token',
            },
        ),
        migrations.AddField("TxdDenuncia", "Token",  models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='app.TxdToken')),
    ]
