# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_txdtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txdchofer',
            name='dpi',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='txddenuncia',
            name='token',
            field=models.ForeignKey(db_column='Token_id', on_delete=django.db.models.deletion.DO_NOTHING, to='app.TxdToken'),
        ),
        migrations.AlterField(
            model_name='txdhorariodetalle',
            name='estado',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
