# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20161018_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='txdduenio',
            name='dpi',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='txdpmt',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='duenio/'),
        ),
    ]
