# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-21 07:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
from django.conf import settings

class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20161021_0151'),
    ]

    operations = [
        migrations.AddField("txdduenio", "usuario", models.ForeignKey(db_column='Usuario_id', null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL)),
        migrations.AddField("txdpmt", "usuario", models.ForeignKey(db_column='Usuario_id',  null=True, on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL)),
    ]
